name: Fly Deploy Production
on:
  push:
    branches:
      - production
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ROLLBAR_API_KEY: ${{ secrets.ROLLBAR_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c packages/nouns-api/fly.toml
